kind = "DojoModel"
class_hash = "0x45fa0f078cce45ced55414239da6e7b440633ec4297105394dee3c234482866"
original_class_hash = "0x45fa0f078cce45ced55414239da6e7b440633ec4297105394dee3c234482866"
abi = "manifests/dev/base/abis/models/nums-Jackpot-723709fc.json"
tag = "nums-Jackpot"
qualified_path = "nums::models::jackpot::jackpot::jackpot"
manifest_name = "nums-Jackpot-723709fc"

[[members]]
name = "jackpot_id"
type = "u32"
key = true

[[members]]
name = "title"
type = "felt252"
key = false

[[members]]
name = "creator"
type = "ContractAddress"
key = false

[[members]]
name = "mode"
type = "JackpotMode"
key = false

[[members]]
name = "expiration"
type = "u64"
key = false

[[members]]
name = "powerups"
type = "bool"
key = false

[[members]]
name = "token"
type = "Option<Token>"
key = false

[[members]]
name = "winner"
type = "Option<ContractAddress>"
key = false

[[members]]
name = "claimed"
type = "bool"
key = false

[[members]]
name = "verified"
type = "bool"
key = false
