kind = "DojoModel"
class_hash = "0x50af3b457e3f167ed69046018bb4b30cb1ac4679cb3a659b4fe1dd505f724e5"
original_class_hash = "0x50af3b457e3f167ed69046018bb4b30cb1ac4679cb3a659b4fe1dd505f724e5"
abi = "manifests/dev/base/abis/models/nums-JackpotCreated-2316c670.json"
tag = "nums-JackpotCreated"
qualified_path = "nums::systems::jackpot_actions::jackpot_actions::jackpot_created"
manifest_name = "nums-JackpotCreated-2316c670"

[[members]]
name = "jackpot_id"
type = "u32"
key = true

[[members]]
name = "token"
type = "Option<Token>"
key = false
