kind = "DojoModel"
class_hash = "0x64cfdefe945782c60f8090b22768566924df9d14f16a36ab5966e574182b208"
original_class_hash = "0x64cfdefe945782c60f8090b22768566924df9d14f16a36ab5966e574182b208"
abi = "manifests/dev/base/abis/models/nums-Inserted-68a8cf4a.json"
tag = "nums-Inserted"
qualified_path = "nums::systems::game_actions::game_actions::inserted"
manifest_name = "nums-Inserted-68a8cf4a"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "index"
type = "u8"
key = false

[[members]]
name = "number"
type = "u16"
key = false

[[members]]
name = "next_number"
type = "u16"
key = false

[[members]]
name = "remaining_slots"
type = "u8"
key = false
