kind = "DojoModel"
class_hash = "0x62af88faf587ddb2d56c2846db472a409df6240b635ae62933253e39efb88ab"
original_class_hash = "0x62af88faf587ddb2d56c2846db472a409df6240b635ae62933253e39efb88ab"
abi = "manifests/dev/base/abis/models/nums-JackpotClaimed-175ae387.json"
tag = "nums-JackpotClaimed"
qualified_path = "nums::systems::jackpot_actions::jackpot_actions::jackpot_claimed"
manifest_name = "nums-JackpotClaimed-175ae387"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "jackpot_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = false
