[world]
name = "Nums"
seed = "nums"
description = "On chain version of the Number Challenge or Blind Number Challenge game."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://nums.gg"


[namespace]
default = "nums"

[env]
rpc_url = "http://localhost:5050"
account_address = "0x5688081f68f4e1d826da33a21bf7a0e1cb882920f230d40ecac902a4dd7ddd"
private_key = "0x230d17156789df0f4e6a117b9255383a90f948b5bcddba4abd3e9a283331204"
world_address = "0x13a0e134c64c01c2a85c014cf51fbd25cf7ba92d7f4b85c3ce0da967e92ed2a"