kind = "DojoModel"
class_hash = "0x11edf83d746011b4eb5143b68ee14f13296087c7a0cfb92d22a6b22fc7ad1f"
original_class_hash = "0x11edf83d746011b4eb5143b68ee14f13296087c7a0cfb92d22a6b22fc7ad1f"
abi = "manifests/mainnet/base/abis/models/nums-Reward-5a0970e8.json"
tag = "nums-Reward"
qualified_path = "nums::models::game::reward"
manifest_name = "nums-Reward-5a0970e8"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "total_rewards"
type = "u32"
key = false

[[members]]
name = "next_reward"
type = "u16"
key = false
