kind = "DojoContract"
class_hash = "0x521759df2489b7c743e19ff7761f1eaa00e63b76eb2a2e381b6af7cfd63161c"
original_class_hash = "0x521759df2489b7c743e19ff7761f1eaa00e63b76eb2a2e381b6af7cfd63161c"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/nums-jackpot_actions-54db86b6.json"
reads = []
writes = []
init_calldata = []
tag = "nums-jackpot_actions"
systems = ["claim_jackpot"]
manifest_name = "nums-jackpot_actions-54db86b6"
