kind = "DojoContract"
class_hash = "0x353d2e47b0c9c804b0fab9307ae0a8fb37d011e730b03ffdfe56cfb19e9daa8"
original_class_hash = "0x353d2e47b0c9c804b0fab9307ae0a8fb37d011e730b03ffdfe56cfb19e9daa8"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/nums-jackpot_actions-54db86b6.json"
reads = []
writes = []
init_calldata = []
tag = "nums-jackpot_actions"
systems = ["claim_jackpot"]
manifest_name = "nums-jackpot_actions-54db86b6"
