kind = "DojoContract"
class_hash = "0x43f162ecaeb8c8e92a59887718ffde5e143ee93b79871ac83c0d25e78403bb5"
original_class_hash = "0x43f162ecaeb8c8e92a59887718ffde5e143ee93b79871ac83c0d25e78403bb5"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/nums-game_actions-4a30d499.json"
reads = []
writes = []
init_calldata = []
tag = "nums-game_actions"
systems = [
    "set_config",
    "set_name",
]
manifest_name = "nums-game_actions-4a30d499"
