kind = "DojoContract"
class_hash = "0x18ac1fe831422b7d7c7d3470c5ab819790c399d797a3ec5cdb06b0177015fc1"
original_class_hash = "0x18ac1fe831422b7d7c7d3470c5ab819790c399d797a3ec5cdb06b0177015fc1"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/nums-game_actions-4a30d499.json"
reads = []
writes = []
init_calldata = []
tag = "nums-game_actions"
systems = [
    "set_config",
    "set_name",
]
manifest_name = "nums-game_actions-4a30d499"
