kind = "DojoContract"
class_hash = "0x6eb9011115364ecb5ded330e3da72a04b7de7900a4e7cc5d8d1b1f270102a98"
original_class_hash = "0x6eb9011115364ecb5ded330e3da72a04b7de7900a4e7cc5d8d1b1f270102a98"
base_class_hash = "0x0"
abi = "manifests/mainnet/base/abis/contracts/nums-actions-2017c0bd.json"
reads = []
writes = []
init_calldata = []
tag = "nums-actions"
systems = [
    "set_config",
    "set_name",
    "claim_jackpot",
]
manifest_name = "nums-actions-2017c0bd"
