kind = "DojoContract"
class_hash = "0x5c780220fe0c3f77ffd4b92da1d586601ae5f0797131df3e35d0a803f848dcc"
original_class_hash = "0x5c780220fe0c3f77ffd4b92da1d586601ae5f0797131df3e35d0a803f848dcc"
base_class_hash = "0x0"
abi = "manifests/mainnet/base/abis/contracts/nums-game_actions-4a30d499.json"
reads = []
writes = []
init_calldata = []
tag = "nums-game_actions"
systems = [
    "set_config",
    "set_name",
]
manifest_name = "nums-game_actions-4a30d499"
