[world]
kind = "WorldContract"
class_hash = "0x32fb65ebfe6d91bb4b7ba0640650722c43ca0c917f5fc0f649ee2ecf720cde"
original_class_hash = "0x32fb65ebfe6d91bb4b7ba0640650722c43ca0c917f5fc0f649ee2ecf720cde"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x1cc6503beb238fa8c3c07dee65da825ab2bde8317689dd42c3dbba4379cb6ef"
transaction_hash = "0x141d75ee64c4e92dd3d849d5d09c832dc2b07715f12c7bcb3c6b9e18e5fefce"
block_number = 3
seed = "nums"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x1f6100e30fc2978767a0d24f3c197d888b195a77fe7efcb39843f768692a6af"
class_hash = "0x2cf6647af7ce46762bf1b5f842bb04483386a29af1e18689888589298fa9af2"
original_class_hash = "0x2cf6647af7ce46762bf1b5f842bb04483386a29af1e18689888589298fa9af2"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/nums-actions-2017c0bd.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "nums-actions"
manifest_name = "nums-actions-2017c0bd"

[[models]]
kind = "DojoModel"
class_hash = "0x82c03d71d17d5baefafa60369e7799d4effa35843e4616d75a72efae5bf34d"
original_class_hash = "0x82c03d71d17d5baefafa60369e7799d4effa35843e4616d75a72efae5bf34d"
abi = "manifests/dev/deployment/abis/models/nums-Config-73ebe747.json"
tag = "nums-Config"
manifest_name = "nums-Config-73ebe747"

[[models.members]]
name = "world_resource"
type = "felt252"
key = true

[[models.members]]
name = "game"
type = "Option<GameConfig>"
key = false

[[models.members]]
name = "reward"
type = "Option<SlotReward>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3e2f56d1eed40adc4a259d3ef972fa5384e3f117c59fea5c09193f6f2887f04"
original_class_hash = "0x3e2f56d1eed40adc4a259d3ef972fa5384e3f117c59fea5c09193f6f2887f04"
abi = "manifests/dev/deployment/abis/models/nums-Created-11db61a7.json"
tag = "nums-Created"
manifest_name = "nums-Created-11db61a7"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_slots"
type = "u8"
key = false

[[models.members]]
name = "max_number"
type = "u16"
key = false

[[models.members]]
name = "min_number"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5e1064d9c14f83839d81c6516ba84550068446dc9b24d8905feed8e716b94d1"
original_class_hash = "0x5e1064d9c14f83839d81c6516ba84550068446dc9b24d8905feed8e716b94d1"
abi = "manifests/dev/deployment/abis/models/nums-Game-468c6d9d.json"
tag = "nums-Game"
manifest_name = "nums-Game-468c6d9d"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_slots"
type = "u8"
key = false

[[models.members]]
name = "max_number"
type = "u16"
key = false

[[models.members]]
name = "min_number"
type = "u16"
key = false

[[models.members]]
name = "remaining_slots"
type = "u8"
key = false

[[models.members]]
name = "next_number"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1bb83775173a286fc59e1b96facb0bc058b2903e4a76f6c1b8cb5aa2c70291"
original_class_hash = "0x1bb83775173a286fc59e1b96facb0bc058b2903e4a76f6c1b8cb5aa2c70291"
abi = "manifests/dev/deployment/abis/models/nums-Inserted-68a8cf4a.json"
tag = "nums-Inserted"
manifest_name = "nums-Inserted-68a8cf4a"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u8"
key = false

[[models.members]]
name = "number"
type = "u16"
key = false

[[models.members]]
name = "next_number"
type = "u16"
key = false

[[models.members]]
name = "remaining_slots"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x330dd35108e8231b4d16712308577ad63d310bb3fe7bf0faf9bdac521e7ad2a"
original_class_hash = "0x330dd35108e8231b4d16712308577ad63d310bb3fe7bf0faf9bdac521e7ad2a"
abi = "manifests/dev/deployment/abis/models/nums-Jackpot-723709fc.json"
tag = "nums-Jackpot"
manifest_name = "nums-Jackpot-723709fc"

[[models.members]]
name = "jackpot_id"
type = "u32"
key = true

[[models.members]]
name = "winner"
type = "Option<ContractAddress>"
key = false

[[models.members]]
name = "token"
type = "ContractAddress"
key = false

[[models.members]]
name = "entry_fee"
type = "u256"
key = false

[[models.members]]
name = "total"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2c2c77431bbcd678c7cbc4b2edc2e8a5c0d0617ab509f71f5e0e932dceaa4a2"
original_class_hash = "0x2c2c77431bbcd678c7cbc4b2edc2e8a5c0d0617ab509f71f5e0e932dceaa4a2"
abi = "manifests/dev/deployment/abis/models/nums-JackpotIncreased-30a7078a.json"
tag = "nums-JackpotIncreased"
manifest_name = "nums-JackpotIncreased-30a7078a"

[[models.members]]
name = "jackpot_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "increased_amount"
type = "u256"
key = false

[[models.members]]
name = "total"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2518088af405be4a6708995bad142b364758cb6a63ba83370b6936434a8269e"
original_class_hash = "0x2518088af405be4a6708995bad142b364758cb6a63ba83370b6936434a8269e"
abi = "manifests/dev/deployment/abis/models/nums-Name-3d781391.json"
tag = "nums-Name"
manifest_name = "nums-Name-3d781391"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x756bcc7b327444dbabe7f8bb71118bbceda7ad7693c8e49ecb2cc10f3801a86"
original_class_hash = "0x756bcc7b327444dbabe7f8bb71118bbceda7ad7693c8e49ecb2cc10f3801a86"
abi = "manifests/dev/deployment/abis/models/nums-Rewarded-6a8b1a15.json"
tag = "nums-Rewarded"
manifest_name = "nums-Rewarded-6a8b1a15"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "token"
type = "ContractAddress"
key = false

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x48c13506e7b85651f67b837ad9011bcf04bf3e05def6b958a9fef183159db7f"
original_class_hash = "0x48c13506e7b85651f67b837ad9011bcf04bf3e05def6b958a9fef183159db7f"
abi = "manifests/dev/deployment/abis/models/nums-Slot-7ef98499.json"
tag = "nums-Slot"
manifest_name = "nums-Slot-7ef98499"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u8"
key = true

[[models.members]]
name = "number"
type = "u16"
key = false
