kind = "DojoModel"
class_hash = "0x22317d1e2e395fda19418777edff53f518cf61c2ec188a46b90c83bec29f4b0"
original_class_hash = "0x22317d1e2e395fda19418777edff53f518cf61c2ec188a46b90c83bec29f4b0"
abi = "manifests/release/base/abis/models/nums-Config-73ebe747.json"
tag = "nums-Config"
qualified_path = "nums::models::config::config"
manifest_name = "nums-Config-73ebe747"

[[members]]
name = "world_resource"
type = "felt252"
key = true

[[members]]
name = "game"
type = "Option<GameConfig>"
key = false

[[members]]
name = "reward"
type = "Option<SlotReward>"
key = false
