kind = "DojoModel"
class_hash = "0x73348bd3a0316593c2a6f98cd9ade23b7ea1f8c1de3ea0c8fc465f7c665b566"
original_class_hash = "0x73348bd3a0316593c2a6f98cd9ade23b7ea1f8c1de3ea0c8fc465f7c665b566"
abi = "manifests/release/base/abis/models/nums-Jackpot-723709fc.json"
tag = "nums-Jackpot"
qualified_path = "nums::models::jackpot::jackpot"
manifest_name = "nums-Jackpot-723709fc"

[[members]]
name = "jackpot_id"
type = "u32"
key = true

[[members]]
name = "winner"
type = "Option<ContractAddress>"
key = false

[[members]]
name = "token"
type = "ContractAddress"
key = false

[[members]]
name = "entry_fee"
type = "u256"
key = false

[[members]]
name = "total"
type = "u256"
key = false
