[world]
kind = "WorldContract"
class_hash = "0x5c4271c8cd454ceb8049d2b0724c99d12c2ef8077fc6ad325b18978f614aab0"
original_class_hash = "0x5c4271c8cd454ceb8049d2b0724c99d12c2ef8077fc6ad325b18978f614aab0"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x71139cb86910386c4e94f97cef55461fdd84711a529a151cdb1b64a2c9cf894"
transaction_hash = "0x27474bc0139e153e00529e209c3d8a35b36d8cded40da375d1f80de4151eadf"
block_number = 209316
seed = "nums"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x4de75e0f02b197883d12d8e482aa98e13a476b7cf5860f0f5445279d28d0aa6"
class_hash = "0x322a9db3f862856487b730641596b384f934330eb82976ba7ac9991ab444fa7"
original_class_hash = "0x322a9db3f862856487b730641596b384f934330eb82976ba7ac9991ab444fa7"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/nums-game_actions-4a30d499.json"
reads = []
writes = []
init_calldata = []
tag = "nums-game_actions"
systems = [
    "set_config",
    "set_name",
]
manifest_name = "nums-game_actions-4a30d499"

[[contracts]]
kind = "DojoContract"
address = "0x2bbabf6d7bfdcf570890e02648004b1c5ec1aaa17be81779b384abe28078eba"
class_hash = "0x49f039b479677ac6f3d47dcd1426dc12d9c3e2371f902b041252ce45bb73fa8"
original_class_hash = "0x49f039b479677ac6f3d47dcd1426dc12d9c3e2371f902b041252ce45bb73fa8"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/nums-jackpot_actions-54db86b6.json"
reads = []
writes = []
init_calldata = []
tag = "nums-jackpot_actions"
systems = ["claim_jackpot"]
manifest_name = "nums-jackpot_actions-54db86b6"

[[models]]
kind = "DojoModel"
class_hash = "0x3975496c291fcb4f04808aea61be4b9ae37c91e89b9cb98c548d09ad367f482"
original_class_hash = "0x3975496c291fcb4f04808aea61be4b9ae37c91e89b9cb98c548d09ad367f482"
abi = "manifests/dev/deployment/abis/models/nums-Config-73ebe747.json"
tag = "nums-Config"
qualified_path = "nums::models::config::config"
manifest_name = "nums-Config-73ebe747"

[[models.members]]
name = "world_resource"
type = "felt252"
key = true

[[models.members]]
name = "game"
type = "Option<GameConfig>"
key = false

[[models.members]]
name = "reward"
type = "Option<SlotReward>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5e9c0224590a2780e65b2e38f2a592fdbb7cccf0d407462884df6da0dd87a6b"
original_class_hash = "0x5e9c0224590a2780e65b2e38f2a592fdbb7cccf0d407462884df6da0dd87a6b"
abi = "manifests/dev/deployment/abis/models/nums-Game-468c6d9d.json"
tag = "nums-Game"
qualified_path = "nums::models::game::game"
manifest_name = "nums-Game-468c6d9d"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_slots"
type = "u8"
key = false

[[models.members]]
name = "max_number"
type = "u16"
key = false

[[models.members]]
name = "min_number"
type = "u16"
key = false

[[models.members]]
name = "remaining_slots"
type = "u8"
key = false

[[models.members]]
name = "next_number"
type = "u16"
key = false

[[models.members]]
name = "jackpot_id"
type = "Option<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x67499b3089307162959114402eae1309abf589160f1f67c273becad4d7b7150"
original_class_hash = "0x67499b3089307162959114402eae1309abf589160f1f67c273becad4d7b7150"
abi = "manifests/dev/deployment/abis/models/nums-GameCreated-613f127a.json"
tag = "nums-GameCreated"
qualified_path = "nums::systems::game_actions::game_actions::game_created"
manifest_name = "nums-GameCreated-613f127a"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_slots"
type = "u8"
key = false

[[models.members]]
name = "max_number"
type = "u16"
key = false

[[models.members]]
name = "min_number"
type = "u16"
key = false

[[models.members]]
name = "jackpot_id"
type = "Option<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x64cfdefe945782c60f8090b22768566924df9d14f16a36ab5966e574182b208"
original_class_hash = "0x64cfdefe945782c60f8090b22768566924df9d14f16a36ab5966e574182b208"
abi = "manifests/dev/deployment/abis/models/nums-Inserted-68a8cf4a.json"
tag = "nums-Inserted"
qualified_path = "nums::systems::game_actions::game_actions::inserted"
manifest_name = "nums-Inserted-68a8cf4a"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u8"
key = false

[[models.members]]
name = "number"
type = "u16"
key = false

[[models.members]]
name = "next_number"
type = "u16"
key = false

[[models.members]]
name = "remaining_slots"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x140eecaa1e7a3c531d5a652d5e5c3fb0c848b2cefb705de15351c75db43c28c"
original_class_hash = "0x140eecaa1e7a3c531d5a652d5e5c3fb0c848b2cefb705de15351c75db43c28c"
abi = "manifests/dev/deployment/abis/models/nums-Jackpot-723709fc.json"
tag = "nums-Jackpot"
qualified_path = "nums::models::jackpot::jackpot"
manifest_name = "nums-Jackpot-723709fc"

[[models.members]]
name = "jackpot_id"
type = "u32"
key = true

[[models.members]]
name = "win_condition"
type = "u8"
key = false

[[models.members]]
name = "winner"
type = "Option<ContractAddress>"
key = false

[[models.members]]
name = "info"
type = "Option<Info>"
key = false

[[models.members]]
name = "token"
type = "Token"
key = false

[[models.members]]
name = "fee"
type = "Option<Fee>"
key = false

[[models.members]]
name = "powerups"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x42b45b5b3a4d23929c8ea5210d76a86ba6a937eb03efd6c377e3aed7892e956"
original_class_hash = "0x42b45b5b3a4d23929c8ea5210d76a86ba6a937eb03efd6c377e3aed7892e956"
abi = "manifests/dev/deployment/abis/models/nums-JackpotClaimed-175ae387.json"
tag = "nums-JackpotClaimed"
qualified_path = "nums::systems::jackpot_actions::jackpot_actions::jackpot_claimed"
manifest_name = "nums-JackpotClaimed-175ae387"

[[models.members]]
name = "jackpot_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7dee8e1a7a4d23ba83256bc5a757d7df5ef96d5af1e7454f58bca06e4c610f1"
original_class_hash = "0x7dee8e1a7a4d23ba83256bc5a757d7df5ef96d5af1e7454f58bca06e4c610f1"
abi = "manifests/dev/deployment/abis/models/nums-JackpotCreated-2316c670.json"
tag = "nums-JackpotCreated"
qualified_path = "nums::systems::jackpot_actions::jackpot_actions::jackpot_created"
manifest_name = "nums-JackpotCreated-2316c670"

[[models.members]]
name = "jackpot_id"
type = "u32"
key = true

[[models.members]]
name = "token"
type = "Token"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x20a00608ef3028157b51b05a51526fd3c3888026f91073f9b1f7dc01690dfc1"
original_class_hash = "0x20a00608ef3028157b51b05a51526fd3c3888026f91073f9b1f7dc01690dfc1"
abi = "manifests/dev/deployment/abis/models/nums-Name-3d781391.json"
tag = "nums-Name"
qualified_path = "nums::models::name::name"
manifest_name = "nums-Name-3d781391"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x11edf83d746011b4eb5143b68ee14f13296087c7a0cfb92d22a6b22fc7ad1f"
original_class_hash = "0x11edf83d746011b4eb5143b68ee14f13296087c7a0cfb92d22a6b22fc7ad1f"
abi = "manifests/dev/deployment/abis/models/nums-Reward-5a0970e8.json"
tag = "nums-Reward"
qualified_path = "nums::models::game::reward"
manifest_name = "nums-Reward-5a0970e8"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "total_rewards"
type = "u32"
key = false

[[models.members]]
name = "next_reward"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7b7eae9dcff3e665a5591e0a77e932273957127353d7d2f5fb7324d015a7bb6"
original_class_hash = "0x7b7eae9dcff3e665a5591e0a77e932273957127353d7d2f5fb7324d015a7bb6"
abi = "manifests/dev/deployment/abis/models/nums-Slot-7ef98499.json"
tag = "nums-Slot"
qualified_path = "nums::models::slot::slot"
manifest_name = "nums-Slot-7ef98499"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u8"
key = true

[[models.members]]
name = "number"
type = "u16"
key = false
