kind = "DojoModel"
class_hash = "0x56ac3e144b43fae8775fd31f44c1714f816cbbf8af4fa0a9771cc0b4a752782"
original_class_hash = "0x56ac3e144b43fae8775fd31f44c1714f816cbbf8af4fa0a9771cc0b4a752782"
abi = "manifests/sepolia/base/abis/models/nums-Inserted-68a8cf4a.json"
tag = "nums-Inserted"
qualified_path = "nums::systems::actions::actions::inserted"
manifest_name = "nums-Inserted-68a8cf4a"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "index"
type = "u8"
key = false

[[members]]
name = "number"
type = "u16"
key = false

[[members]]
name = "next_number"
type = "u16"
key = false

[[members]]
name = "remaining_slots"
type = "u8"
key = false
