kind = "DojoModel"
class_hash = "0x2ef2c4de37f887c65e206c4d2e53f63e0d9fb91190a6055d6899a586cbb9625"
original_class_hash = "0x2ef2c4de37f887c65e206c4d2e53f63e0d9fb91190a6055d6899a586cbb9625"
abi = "manifests/sepolia/base/abis/models/nums-Rewarded-6a8b1a15.json"
tag = "nums-Rewarded"
qualified_path = "nums::systems::actions::actions::rewarded"
manifest_name = "nums-Rewarded-6a8b1a15"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "token"
type = "ContractAddress"
key = false

[[members]]
name = "amount"
type = "u256"
key = false
