[world]
kind = "WorldContract"
class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
original_class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
abi = "manifests/release/deployment/abis/dojo-world.json"
address = "0x5e29c6454f630f2e25fdc0ceb3eba089152c44a6c8f41ac3dfa58aa499a8e1f"
transaction_hash = "0x5aaa75f06eeacec20cde7457da3b8cf3f20531bb0eb0d7f43c86bb61227421d"
seed = "nums"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "release"
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/release/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x34dd07df0938f3181a2610105a5361ce371b9eaa7a241c62030f0aa1931fdc4"
class_hash = "0x138e551f09fa9c23cdb657d4ae10919148e0f127e054f9c60313b8835c27623"
original_class_hash = "0x138e551f09fa9c23cdb657d4ae10919148e0f127e054f9c60313b8835c27623"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/release/deployment/abis/contracts/nums-actions-2017c0bd.json"
reads = []
writes = []
init_calldata = []
tag = "nums-actions"
systems = [
    "set_config",
    "set_name",
]
manifest_name = "nums-actions-2017c0bd"

[[models]]
kind = "DojoModel"
class_hash = "0x22317d1e2e395fda19418777edff53f518cf61c2ec188a46b90c83bec29f4b0"
original_class_hash = "0x22317d1e2e395fda19418777edff53f518cf61c2ec188a46b90c83bec29f4b0"
abi = "manifests/release/deployment/abis/models/nums-Config-73ebe747.json"
tag = "nums-Config"
qualified_path = "nums::models::config::config"
manifest_name = "nums-Config-73ebe747"

[[models.members]]
name = "world_resource"
type = "felt252"
key = true

[[models.members]]
name = "game"
type = "Option<GameConfig>"
key = false

[[models.members]]
name = "reward"
type = "Option<SlotReward>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x9d63a7eee4dda1d021c0f82b6524561779f7dc16b396fdbc6c859f3f8470ba"
original_class_hash = "0x9d63a7eee4dda1d021c0f82b6524561779f7dc16b396fdbc6c859f3f8470ba"
abi = "manifests/release/deployment/abis/models/nums-Created-11db61a7.json"
tag = "nums-Created"
qualified_path = "nums::systems::actions::actions::created"
manifest_name = "nums-Created-11db61a7"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_slots"
type = "u8"
key = false

[[models.members]]
name = "max_number"
type = "u16"
key = false

[[models.members]]
name = "min_number"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6822236f4562f10cf9b3af5dfd0a81eca3e6965918b54e870405f8e816cd8fc"
original_class_hash = "0x6822236f4562f10cf9b3af5dfd0a81eca3e6965918b54e870405f8e816cd8fc"
abi = "manifests/release/deployment/abis/models/nums-Game-468c6d9d.json"
tag = "nums-Game"
qualified_path = "nums::models::game::game"
manifest_name = "nums-Game-468c6d9d"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_slots"
type = "u8"
key = false

[[models.members]]
name = "max_number"
type = "u16"
key = false

[[models.members]]
name = "min_number"
type = "u16"
key = false

[[models.members]]
name = "remaining_slots"
type = "u8"
key = false

[[models.members]]
name = "next_number"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x56ac3e144b43fae8775fd31f44c1714f816cbbf8af4fa0a9771cc0b4a752782"
original_class_hash = "0x56ac3e144b43fae8775fd31f44c1714f816cbbf8af4fa0a9771cc0b4a752782"
abi = "manifests/release/deployment/abis/models/nums-Inserted-68a8cf4a.json"
tag = "nums-Inserted"
qualified_path = "nums::systems::actions::actions::inserted"
manifest_name = "nums-Inserted-68a8cf4a"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u8"
key = false

[[models.members]]
name = "number"
type = "u16"
key = false

[[models.members]]
name = "next_number"
type = "u16"
key = false

[[models.members]]
name = "remaining_slots"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x73348bd3a0316593c2a6f98cd9ade23b7ea1f8c1de3ea0c8fc465f7c665b566"
original_class_hash = "0x73348bd3a0316593c2a6f98cd9ade23b7ea1f8c1de3ea0c8fc465f7c665b566"
abi = "manifests/release/deployment/abis/models/nums-Jackpot-723709fc.json"
tag = "nums-Jackpot"
qualified_path = "nums::models::jackpot::jackpot"
manifest_name = "nums-Jackpot-723709fc"

[[models.members]]
name = "jackpot_id"
type = "u32"
key = true

[[models.members]]
name = "winner"
type = "Option<ContractAddress>"
key = false

[[models.members]]
name = "token"
type = "ContractAddress"
key = false

[[models.members]]
name = "entry_fee"
type = "u256"
key = false

[[models.members]]
name = "total"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6af0ee70326252b0566dfdb4dff799081deb0aed9215a7204b18c744a8396bf"
original_class_hash = "0x6af0ee70326252b0566dfdb4dff799081deb0aed9215a7204b18c744a8396bf"
abi = "manifests/release/deployment/abis/models/nums-JackpotIncreased-30a7078a.json"
tag = "nums-JackpotIncreased"
qualified_path = "nums::systems::actions::actions::jackpot_increased"
manifest_name = "nums-JackpotIncreased-30a7078a"

[[models.members]]
name = "jackpot_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "increased_amount"
type = "u256"
key = false

[[models.members]]
name = "total"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x20a00608ef3028157b51b05a51526fd3c3888026f91073f9b1f7dc01690dfc1"
original_class_hash = "0x20a00608ef3028157b51b05a51526fd3c3888026f91073f9b1f7dc01690dfc1"
abi = "manifests/release/deployment/abis/models/nums-Name-3d781391.json"
tag = "nums-Name"
qualified_path = "nums::models::name::name"
manifest_name = "nums-Name-3d781391"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2ef2c4de37f887c65e206c4d2e53f63e0d9fb91190a6055d6899a586cbb9625"
original_class_hash = "0x2ef2c4de37f887c65e206c4d2e53f63e0d9fb91190a6055d6899a586cbb9625"
abi = "manifests/release/deployment/abis/models/nums-Rewarded-6a8b1a15.json"
tag = "nums-Rewarded"
qualified_path = "nums::systems::actions::actions::rewarded"
manifest_name = "nums-Rewarded-6a8b1a15"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "token"
type = "ContractAddress"
key = false

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7b7eae9dcff3e665a5591e0a77e932273957127353d7d2f5fb7324d015a7bb6"
original_class_hash = "0x7b7eae9dcff3e665a5591e0a77e932273957127353d7d2f5fb7324d015a7bb6"
abi = "manifests/release/deployment/abis/models/nums-Slot-7ef98499.json"
tag = "nums-Slot"
qualified_path = "nums::models::slot::slot"
manifest_name = "nums-Slot-7ef98499"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u8"
key = true

[[models.members]]
name = "number"
type = "u16"
key = false
