kind = "DojoModel"
class_hash = "0x180f772e8666851a16291698fa8b0c7804c6501095bbbf649cf2147bdfe11bc"
original_class_hash = "0x180f772e8666851a16291698fa8b0c7804c6501095bbbf649cf2147bdfe11bc"
abi = "manifests/dev/abis/base/models/number_challenge_models_slot_slot.json"
name = "number_challenge::models::slot::slot"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "slot"
type = "u8"
key = true

[[members]]
name = "number"
type = "u16"
key = false
