kind = "DojoModel"
class_hash = "0x4e8dfa0aa01bce92bbf8ada6264419959f5e2bb1a556cecb3a6b4abcc2114a8"
original_class_hash = "0x4e8dfa0aa01bce92bbf8ada6264419959f5e2bb1a556cecb3a6b4abcc2114a8"
abi = "manifests/dev/abis/base/models/number_challenge_models_game_game.json"
name = "number_challenge::models::game::game"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "max_slots"
type = "u8"
key = false

[[members]]
name = "remaining_slots"
type = "u8"
key = false

[[members]]
name = "max_number"
type = "u16"
key = false

[[members]]
name = "next_number"
type = "u16"
key = false
