kind = "DojoModel"
class_hash = "0x1bb83775173a286fc59e1b96facb0bc058b2903e4a76f6c1b8cb5aa2c70291"
original_class_hash = "0x1bb83775173a286fc59e1b96facb0bc058b2903e4a76f6c1b8cb5aa2c70291"
abi = "manifests/dev/base/abis/models/nums-Inserted-68a8cf4a.json"
tag = "nums-Inserted"
manifest_name = "nums-Inserted-68a8cf4a"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "index"
type = "u8"
key = false

[[members]]
name = "number"
type = "u16"
key = false

[[members]]
name = "next_number"
type = "u16"
key = false

[[members]]
name = "remaining_slots"
type = "u8"
key = false
