kind = "DojoContract"
class_hash = "0x60854500421cf55f9b86ce3670bfc4184af44720b1ba5ef7184ce06edd56170"
original_class_hash = "0x60854500421cf55f9b86ce3670bfc4184af44720b1ba5ef7184ce06edd56170"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/nums-jackpot_actions-54db86b6.json"
reads = []
writes = []
init_calldata = []
tag = "nums-jackpot_actions"
systems = [
    "claim",
    "king_me",
    "verify",
]
manifest_name = "nums-jackpot_actions-54db86b6"
