kind = "DojoContract"
class_hash = "0x49f039b479677ac6f3d47dcd1426dc12d9c3e2371f902b041252ce45bb73fa8"
original_class_hash = "0x49f039b479677ac6f3d47dcd1426dc12d9c3e2371f902b041252ce45bb73fa8"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/nums-jackpot_actions-54db86b6.json"
reads = []
writes = []
init_calldata = []
tag = "nums-jackpot_actions"
systems = ["claim_jackpot"]
manifest_name = "nums-jackpot_actions-54db86b6"
