kind = "DojoContract"
class_hash = "0x1e81df4811f504bba66ffd751fec18125799f5df92286ee8dd2613657aedd8e"
original_class_hash = "0x1e81df4811f504bba66ffd751fec18125799f5df92286ee8dd2613657aedd8e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/nums-actions-2017c0bd.json"
reads = []
writes = []
init_calldata = []
tag = "nums-actions"
systems = [
    "set_config",
    "set_name",
    "claim_jackpot",
]
manifest_name = "nums-actions-2017c0bd"
