kind = "DojoContract"
class_hash = "0x3b6991c78268ca9ac12012a3bb174c013e2b676f598822e69712e790b0998e"
original_class_hash = "0x3b6991c78268ca9ac12012a3bb174c013e2b676f598822e69712e790b0998e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/nums-game_actions-4a30d499.json"
reads = []
writes = []
init_calldata = []
tag = "nums-game_actions"
systems = [
    "set_config",
    "set_name",
]
manifest_name = "nums-game_actions-4a30d499"
