kind = "DojoContract"
class_hash = "0x322a9db3f862856487b730641596b384f934330eb82976ba7ac9991ab444fa7"
original_class_hash = "0x322a9db3f862856487b730641596b384f934330eb82976ba7ac9991ab444fa7"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/nums-game_actions-4a30d499.json"
reads = []
writes = []
init_calldata = []
tag = "nums-game_actions"
systems = [
    "set_config",
    "set_name",
]
manifest_name = "nums-game_actions-4a30d499"
