[package]
cairo-version = "2.5.4"
name = "number_challenge"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply && ./scripts/default_auth.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/20-number-challenge/katana"
# Default account for katana with seed = 0
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
world_address = "0x2fb9256a503272ddf2606741a969933bc0711e19ae5d08fcb9b147a76dfe3c5" # Update this line with your world address

[tool.dojo.world]
name = "20 Number Challenge"
description = "On chain version of the 20 Number Challenge or Blind Number Challenge game."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://number-challenge.vercel.app"
