[package]
cairo-version = "=2.6.3"
name = "nums"
version = "0.1.0"
edition = "2023_10"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply && ./scripts/default_auth.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.2" }
token = { git = "https://github.com/dojoengine/origami.git" }

[[target.dojo]]

[tool.dojo.env]
rpc_url = "http://localhost:5050"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
#world_address = "0x7dac424af9014f91486c80b4ee8869a438679e01f3f5adb986a4ecbc456a985" 

[tool.dojo.world]
name = "Nums"
description = "On chain version of the Number Challenge or Blind Number Challenge game."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://number-challenge.vercel.app"
