[package]
cairo-version = "2.5.4"
name = "number_challenge"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply && ./scripts/default_auth.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/rpc/starknet-sepolia"
# Default account for katana with seed = 0
account_address = "0x071BA8e0cE57BC942035edF27DE30b199e27B28A60947625eab1249620F3256b"
private_key = "0xc01bfdd65cf046e8b69947c70eb987ad29707cc2f4d8256a5c45392a53c72d"
world_address = "0x2fb9256a503272ddf2606741a969933bc0711e19ae5d08fcb9b147a76dfe3c5" # Update this line with your world address

[tool.dojo.world]
name = "20 Number Challenge"
description = "On chain version of the 20 Number Challenge or Blind Number Challenge game."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://number-challenge.vercel.app"
