[package]
name = "nums_appchain"
version = "0.1.0"
cairo-version = "=2.8.4"
edition = "2024_07"

[[target.starknet-contract]]
sierra = true
casm = true
# It's important to keep this, since it's used by Sozo to check the world version.
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.8" }
starknet = "2.8.4"
nums_common = { path = "../common" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.8" }

[features] 
default = []

[profile.slot]
[profile.mainnet]
[profile.sepolia]