kind = "DojoModel"
class_hash = "0x409cc741dc7c80fd199adabe37a2f4e5d2b76299773bc14b27fc2b9699483e1"
original_class_hash = "0x409cc741dc7c80fd199adabe37a2f4e5d2b76299773bc14b27fc2b9699483e1"
abi = "manifests/dev/abis/base/models/number_challenge_models_game_slot.json"
name = "number_challenge::models::game::slot"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "slot"
type = "u8"
key = true

[[members]]
name = "number"
type = "u16"
key = false
