[package]
name = "nums_tokens"
version = "0.1.0"
edition = "2024_07"
cairo-version = "=2.7.0"

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.1" }
starknet = ">=2.7.0"

[[target.starknet-contract]]
sierra = true
casm = false