[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x6056e94631c0672efd9c79ad7d37baf74f941d1159a0b3aacf4a91ac8138584"
transaction_hash = "0x1581cc5044fe376f92fdc3ed1a79f829a21327a625207f67a4a01449cb9f0a"
block_number = 3
seed = "nums"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x67dd66038866856b3ae934f27cf3509f2eeef5ffa916e92eb48393c6cda7c36"
class_hash = "0x749e1a831c6965010fe031ab88d80c09a5414192561fac872524b4001117509"
original_class_hash = "0x749e1a831c6965010fe031ab88d80c09a5414192561fac872524b4001117509"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/nums_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "nums::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x90f3e716484092167263a0a52372f71c448deb649abed95d2fcec58e8dfa94"
original_class_hash = "0x90f3e716484092167263a0a52372f71c448deb649abed95d2fcec58e8dfa94"
abi = "manifests/dev/abis/deployments/models/nums_models_config_config.json"
name = "nums::models::config::config"

[[models.members]]
name = "world"
type = "felt252"
key = true

[[models.members]]
name = "game"
type = "Option<GameConfig>"
key = false

[[models.members]]
name = "cost"
type = "Option<GameCost>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x62d7c9b7073a063c7fe22dc9011802c36fdf8dff8a6c2cb43b6c62a497bca00"
original_class_hash = "0x62d7c9b7073a063c7fe22dc9011802c36fdf8dff8a6c2cb43b6c62a497bca00"
abi = "manifests/dev/abis/deployments/models/nums_models_game_game.json"
name = "nums::models::game::game"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_slots"
type = "u8"
key = false

[[models.members]]
name = "max_number"
type = "u16"
key = false

[[models.members]]
name = "min_number"
type = "u16"
key = false

[[models.members]]
name = "remaining_slots"
type = "u8"
key = false

[[models.members]]
name = "next_number"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x350e28299d22d10e44a9b582217206ac5d678673435fed4030877929a2379c0"
original_class_hash = "0x350e28299d22d10e44a9b582217206ac5d678673435fed4030877929a2379c0"
abi = "manifests/dev/abis/deployments/models/nums_models_jackpot_jackpot.json"
name = "nums::models::jackpot::jackpot"

[[models.members]]
name = "jackpot_id"
type = "u32"
key = true

[[models.members]]
name = "winner"
type = "Option<ContractAddress>"
key = false

[[models.members]]
name = "token"
type = "ContractAddress"
key = false

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2ec8d1a306d37269643556c7557e5a3f49faf1e83a994040bc3f1f013b05a1a"
original_class_hash = "0x2ec8d1a306d37269643556c7557e5a3f49faf1e83a994040bc3f1f013b05a1a"
abi = "manifests/dev/abis/deployments/models/nums_models_name_name.json"
name = "nums::models::name::name"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x44eaedad7de171214d112329c4f16461d006581d88dc3dfccb59b1fb9cc59a4"
original_class_hash = "0x44eaedad7de171214d112329c4f16461d006581d88dc3dfccb59b1fb9cc59a4"
abi = "manifests/dev/abis/deployments/models/nums_models_slot_slot.json"
name = "nums::models::slot::slot"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u8"
key = true

[[models.members]]
name = "number"
type = "u16"
key = false
