[world]
kind = "WorldContract"
class_hash = "0x249c480cccbaf12d17af89cdbb11fbd145ff2ebed2d108dd75ecdae2c7f80ca"
original_class_hash = "0x249c480cccbaf12d17af89cdbb11fbd145ff2ebed2d108dd75ecdae2c7f80ca"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x623ab17e0ce2fa1a73acb1eb7bd08c90ae7670de0aa03e9703db195ee8d0d9a"
transaction_hash = "0x7078a4a2582e88c9cc096aff659b19ce2068363ef74ed24846176cd2fcd6b7d"
block_number = 3
seed = "number_challenge"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/rpc/starknet-sepolia"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x2eebb648f31d6420d6a3872e1c44c202b046f7e011aa9ce0c1a407b4cc648eb"
class_hash = "0xcfbddd3d404b1437f8390aa021e7297bb8ede142cdce4a2654def39a2eaad2"
original_class_hash = "0xcfbddd3d404b1437f8390aa021e7297bb8ede142cdce4a2654def39a2eaad2"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "manifests/dev/abis/deployments/contracts/number_challenge_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "number_challenge::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x4e8dfa0aa01bce92bbf8ada6264419959f5e2bb1a556cecb3a6b4abcc2114a8"
original_class_hash = "0x4e8dfa0aa01bce92bbf8ada6264419959f5e2bb1a556cecb3a6b4abcc2114a8"
abi = "manifests/dev/abis/deployments/models/number_challenge_models_game_game.json"
name = "number_challenge::models::game::game"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_slots"
type = "u8"
key = false

[[models.members]]
name = "remaining_slots"
type = "u8"
key = false

[[models.members]]
name = "max_number"
type = "u16"
key = false

[[models.members]]
name = "next_number"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x180f772e8666851a16291698fa8b0c7804c6501095bbbf649cf2147bdfe11bc"
original_class_hash = "0x180f772e8666851a16291698fa8b0c7804c6501095bbbf649cf2147bdfe11bc"
abi = "manifests/dev/abis/deployments/models/number_challenge_models_slot_slot.json"
name = "number_challenge::models::slot::slot"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "slot"
type = "u8"
key = true

[[models.members]]
name = "number"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3804aacbedba0a892fc7f23b09c78cdd0bad71ad49ed615211d4df607e63637"
original_class_hash = "0x3804aacbedba0a892fc7f23b09c78cdd0bad71ad49ed615211d4df607e63637"
abi = "manifests/dev/abis/deployments/models/number_challenge_systems_actions_actions_created.json"
name = "number_challenge::systems::actions::actions::created"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_slots"
type = "u8"
key = false

[[models.members]]
name = "max_number"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x39c9138c8d936a9146cce7b39270781656dc9a81260c5be34d00338cb76a671"
original_class_hash = "0x39c9138c8d936a9146cce7b39270781656dc9a81260c5be34d00338cb76a671"
abi = "manifests/dev/abis/deployments/models/number_challenge_systems_actions_actions_inserted.json"
name = "number_challenge::systems::actions::actions::inserted"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "slot"
type = "u8"
key = false

[[models.members]]
name = "number"
type = "u16"
key = false

[[models.members]]
name = "next_number"
type = "u16"
key = false

[[models.members]]
name = "remaining_slots"
type = "u8"
key = false
