kind = "DojoContract"
class_hash = "0x50413c0ff64edd115b4a297e15803beace304d8cd76aec37d169c778e3dcdaf"
original_class_hash = "0x50413c0ff64edd115b4a297e15803beace304d8cd76aec37d169c778e3dcdaf"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/number_challenge_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "number_challenge::systems::actions::actions"
